name: SlapperParticlesV2
version: 2.0.2
api: [5.0.0]
main: xqwtxon\SlapperParticlesV2\Main
src-namespace-prefix: xqwtxon\SlapperParticlesV2
depend: Slapper
author: xqwtxon, Terpz710
description: Slapper have now particles!
